/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWellnessRouteImport } from './routes/app.wellness'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppPlacementsRouteImport } from './routes/app.placements'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppGroupsRouteImport } from './routes/app.groups'
import { Route as AppFocusRouteImport } from './routes/app.focus'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementsRoute = AppPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppFocusRoute = AppFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/focus': typeof AppFocusRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/focus': typeof AppFocusRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/focus': typeof AppFocusRoute
  '/app/groups': typeof AppGroupsRoute
  '/app/notes': typeof AppNotesRoute
  '/app/placements': typeof AppPlacementsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/wellness': typeof AppWellnessRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/focus'
    | '/app/groups'
    | '/app/notes'
    | '/app/placements'
    | '/app/planner'
    | '/app/resources'
    | '/app/settings'
    | '/app/wellness'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/focus'
    | '/app/groups'
    | '/app/notes'
    | '/app/placements'
    | '/app/planner'
    | '/app/resources'
    | '/app/settings'
    | '/app/wellness'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/assignments'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/focus'
    | '/app/groups'
    | '/app/notes'
    | '/app/placements'
    | '/app/planner'
    | '/app/resources'
    | '/app/settings'
    | '/app/wellness'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wellness': {
      id: '/app/wellness'
      path: '/wellness'
      fullPath: '/app/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/placements': {
      id: '/app/placements'
      path: '/placements'
      fullPath: '/app/placements'
      preLoaderRoute: typeof AppPlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/groups': {
      id: '/app/groups'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/focus': {
      id: '/app/focus'
      path: '/focus'
      fullPath: '/app/focus'
      preLoaderRoute: typeof AppFocusRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppFocusRoute: typeof AppFocusRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppNotesRoute: typeof AppNotesRoute
  AppPlacementsRoute: typeof AppPlacementsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWellnessRoute: typeof AppWellnessRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppFocusRoute: AppFocusRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppNotesRoute: AppNotesRoute,
  AppPlacementsRoute: AppPlacementsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWellnessRoute: AppWellnessRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
